### ISSUE TITLE
Compilation fails with gfortran-13

### ISSUE THREAD

**Issue by auggiemarignier** [inlab-geo/pyrf96#3]
I discovered this when trying to integrate into [`espresso`](https://github.com/inlab-geo/espresso/pull/195).  Everything was going fine locally (`gfortran-14`), then the `espresso` CI [failed](https://github.com/inlab-geo/espresso/actions/runs/12170714517/job/33946229964?pr=195) because the runners only have access to `gfortran-13`.

I downgraded my local `gfortran` to `13` and got the same error.

**Comment by JuergHauser** [comment]
gfortran-13  has a line length limit that is is no longer imposed by gfortran-14.  The solution is to reformat RF90.f90 using line continuation where needed to break long lines.

<img width="1001" alt="Screenshot 2024-12-05 at 12 22 27" src="https://github.com/user-attachments/assets/9bf7bfd6-32d0-41f1-9c31-5e56b0a989bf">
