### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by auggiemarignier** [inlab-geo/pyrf96#5]
In order for this to be a dependency of packages that are hosted on PyPI (i.e. `espresso`) this also needs to be added to PyPI.  See [here](https://github.com/inlab-geo/espresso/actions/runs/12245525476/job/34160261837#step:4:113).

It shouldn't be a difficult job.

@msambridge @JuergHauser are you alright with this?

**Comment by msambridge** [comment]
Fine by me.

On 10 Dec 2024, at 10:01 am, auggiemarignier ***@***.***> wrote:



In order for this to be a dependency of packages that are hosted on PyPI (i.e. espresso) this also needs to be added to PyPI. See here<https://github.com/inlab-geo/espresso/actions/runs/12245525476/job/34160261837#step:4:113>.

It shouldn't be a difficult job.

@msambridge<https://github.com/msambridge> @JuergHauser<https://github.com/JuergHauser> are you alright with this?

**Comment by auggiemarignier** [comment]
#6
